theme: minima
title: Mikael's musings and ramblings on DevOps, Cloud, and Software Development
description: More than anything, this blog will serve as a place for me to document my learnings and share my thoughts on DevOps, Cloud, and Software Development.
author: Mikael Lognseth