remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Mikael's musings and ramblings on DevOps, Cloud, and Software Development
description: More than anything, this blog will serve as a place for me to document my learnings and share my thoughts on DevOps, Cloud, and Software Development.
author: Mikael Lognseth
